### ISSUE TITLE
tilde operator not resolving to home directory

### ISSUE THREAD

**Issue by ThangaAyyanar** [Davejkane/riv#43] opened 2019-05-13 18:05 UTC
riv ~/Desktop/*.png doesnot load any image

**Comment by Davejkane** [comment] 2019-05-13 20:31
I'll close this issue as it is a duplicate of [#44](https://github.com/Davejkane/riv/issues/44). The fix will come soon, probably tomorrow.

**Closed as completed by Davejkane** 2019-05-13 20:31 UTC
